version: '3.8'
name: lyprox

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/srv/www/lyprox/static
      - media_volume:/srv/www/lyprox/media
    depends_on:
      - webapp
    restart: "on-failure"

  webapp:
    build: .
    command: sh -c "manage.py makemigrations --noinput &&
                    manage.py migrate --noinput &&
                    manage.py collectstatic --noinput &&
                    gunicorn -c gunicorn.conf.py"
    env_file:
      - .env
    volumes:
      - static_volume:/srv/www/lyprox/static
      - media_volume:/srv/www/lyprox/media
    expose:
      - 8000

volumes:
  static_volume:
  media_volume:
