version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/srv/www/static
      - media_volume:/srv/www/media
    depends_on:
      - webapp
    restart: "on-failure"

  webapp:
    build: .
    command: sh -c "manage.py makemigrations --noinput &&
                    manage.py migrate --noinput &&
                    manage.py collectstatic --noinput &&
                    manage.py init_institutions &&
                    manage.py init_users &&
                    manage.py init_datasets &&
                    manage.py init_riskmodels &&
                    gunicorn -c gunicorn.conf.py"
    env_file:
      - .env
    volumes:
      - static_volume:/srv/www/static
      - media_volume:/srv/www/media
    expose:
      - ${DJANGO_GUNICORN_PORT}

volumes:
  static_volume:
  media_volume:
