[build-system]
requires = [
    "setuptools >= 61.0.0",
    "setuptools_scm >= 7.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "lyprox"
description = "Web app for exploring patterns and correlations in the lymph node level involvements of head & neck cancer patients."
authors = [
    {name = "Roman Ludwig", email = "roman.ludwig@usz.ch"}
]
readme = "README.md"
requires-python = "~=3.8"
dependencies = [
    "Django ~= 3.2.5",
    "django-filter ~= 2.4",
    "django-address ~= 0.2",
    "django-phonenumber-field ~= 5.2",
    "phonenumbers ~= 8.12",
    "django-auth-logger ~= 2.1",
    "Markdown ~= 3.3",
    "numpy ~= 1.21",
    "pandas ~= 1.2",
    "gunicorn ~= 20.1",
]
keywords = ["web app", "head and neck", "cancer", "radiation oncology", "lymph nodes", "metastases"]
license = { text = "MIT"}
dynamic = ["version"]

[project.urls]
source = "https://github.com/rmnldwg/lyprox"
documentation = "https://rmnldwg.github.io/lyprox"

[tool.setuptools_scm]
write_to = "core/_version.py"
local_scheme = "no-local-version"

[tool.setuptools.package-dir]
"lyprox.core" = "core"
"lyprox.accounts" = "accounts"
"lyprox.patients" = "patients"
"lyprox.dashboard" = "dashboard"

[tool.setuptools.dynamic]
version = {attr = "core._version.version"}

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.pycln]
all = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = "test_*.py"
