# Generated by Django 4.2.20 on 2025-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riskpredictor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
