name: Push to Azure VM

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.REPO_NAME }}
          git pull --tags origin main
          .venv/bin/python -m pip install --upgrade pip setuptools setuptools_scm wheel
          .venv/bin/python -m pip install .
          .venv/bin/python manage.py dbbackup --noinput
          .venv/bin/python manage.py migrate --noinput
          .venv/bin/python manage.py collectstatic --noinput
          sudo chown rmnldwg:www-data db.sqlite3
          chmod 664 db.sqlite3
          sudo chown -R rmnldwg:www-data media
          find media/* -type f -exec chmod 664 {} \;
          sudo service apache2 restart
