name: Push to Azure VM

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Hostname where the webapp should be reachable'
        type: string
        required: true
        default: 'lyprox.org'
      port:
        description: 'Port to use on the hosting VM'
        type: number
        required: true
        default: 8000
      pyver:
        description: 'Python version to use'
        type: string
        required: true
        default: '3.10'

  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_KEY }}
        port: 22
        script: |
          TMPFILE=$(mktemp)
          wget https://raw.githubusercontent.com/rmnldwg/lyprox/${{ github.ref_name }}/setup.sh -O $TMPFILE
          bash $TMPFILE -p ${{ inputs.pyver }} -b ${{ github.ref_name }} ${{ inputs.hostname }} ${{ inputs.port }}
          echo 'DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}"' >> /srv/www/${{ inputs.hostname }}/.env
          echo 'GITHUB_TOKEN="${{ secrets.READONLY_TOKEN }}"' >> /srv/www/${{ inputs.hostname }}/.env
          echo '${{ secrets.DJANGO_PASSWORDS }}' >> /srv/www/${{ inputs.hostname }}/.env
          sudo cp /srv/www/${{ inputs.hostname }}/gunicorn@.service /etc/systemd/system/gunicorn@.service
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn@${{ inputs.hostname }}.service
