name: Push to Azure VM

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_KEY }}
        port: 22
        script: |
          TMPFILE=$(mktemp)
          wget https://raw.githubusercontent.com/rmnldwg/lyprox/main/setup.sh -O $TMPFILE
          sudo bash $TMPFILE -p 3.8 lyprox.org
          sudo cp /srv/www/lyprox.org/gunicorn@.service /etc/systemd/system/gunicorn@.service
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn@lyprox.org.service
